import { chromium } from 'playwright'
import { createJob } from '@/lib/db/jobs'
import { normalizeJob } from '@/lib/ai/normalize-job' // Assuming this exists and works

interface ScrapedJob {
  raw_description: string
  source_url: string
  source: string
  company_name: string | null // To help identify/create company
}

/**
 * Scrapes all active job postings from a given Greenhouse job board URL.
 * @param boardUrl The URL of the Greenhouse job board (e.g., https://boards.greenhouse.io/somecompany)
 */
export async function scrapeGreenhouseBoard(boardUrl: string): Promise<void> {
  const browser = await chromium.launch({ headless: true })
  const context = await browser.newContext()
  const page = await context.newPage()

  try {
    await page.goto(boardUrl, { waitUntil: 'domcontentloaded' })
    console.log(`Navigated to Greenhouse board: ${boardUrl}`)

    const companyName = await page.locator('h1.company-name, .company-name h1').first().textContent().catch(() => null)
    console.log(`Detected company name: ${companyName || 'N/A'}`)

    const jobLinks = await page.$$eval('a.job-link', (links: HTMLAnchorElement[]) =>
      links.map(link => link.href)
    )
    console.log(`Found ${jobLinks.length} job links.`)

    for (const jobLink of jobLinks) {
      try {
        await page.goto(jobLink, { waitUntil: 'domcontentloaded' })
        const rawDescription = await page.locator('#content').textContent()
        const jobTitle = await page.locator('h1.app-title').textContent()

        if (rawDescription && jobTitle) {
          console.log(`Scraped job: ${jobTitle} from ${jobLink}`)

          const normalizedData = await normalizeJob(rawDescription)

          await createJob({
            company_id: null, // For now, leave null. We can match/create companies later.
            raw_description: rawDescription,
            normalized_data: normalizedData,
            embedding: null, // Will be generated by AI later
            status: 'active',
            source: 'greenhouse',
            source_url: jobLink,
          })
          console.log(`Stored job: ${jobTitle}`)
        } else {
          console.warn(`Could not scrape raw description or title for job: ${jobLink}`)
        }
      } catch (jobError) {
        console.error(`Error scraping individual job ${jobLink}:`, jobError)
      }
    }
  } catch (error) {
    console.error(`Error scraping Greenhouse board ${boardUrl}:`, error)
  } finally {
    await browser.close()
    console.log('Browser closed.')
  }
}
