import { chromium } from 'playwright'
import { createJob } from '@/lib/db/jobs'
import { normalizeJob } from '@/lib/ai/normalize-job'

/**
 * Scrapes job postings from a given Indeed search results URL.
 * Indeed often uses a complex DOM structure and redirects, so this will be a basic attempt.
 * @param searchUrl The URL of the Indeed search results page.
 */
export async function scrapeIndeedBoard(searchUrl: string): Promise<void> {
  const browser = await chromium.launch({ headless: true })
  const context = await browser.newContext()
  const page = await context.newPage()

  try {
    await page.goto(searchUrl, { waitUntil: 'domcontentloaded' })
    console.log(`Navigated to Indeed search results: ${searchUrl}`)

    // Extract job links from the search results page
    // Indeed job cards often have a data-jk attribute for job key
    const jobLinks = await page.$$eval('a[data-jk]', (links: HTMLAnchorElement[]) =>
      links.map(link => `https://www.indeed.com/viewjob?jk=${link.dataset.jk}`)
    )
    console.log(`Found ${jobLinks.length} job links on Indeed search page.`)

    for (const jobLink of jobLinks) {
      try {
        await page.goto(jobLink, { waitUntil: 'domcontentloaded' })
        // Wait for the job description to load
        await page.waitForSelector('#jobDescriptionText', { timeout: 5000 }).catch(() => {
          console.warn(`Job description selector not found for ${jobLink}, skipping.`)
          return null
        })

        const rawDescription = await page.locator('#jobDescriptionText').textContent()
        const jobTitle = await page.locator('.jobsearch-JobInfoHeader-title span').first().textContent()
        const companyName = await page.locator('[data-testid="inlineHeader-companyName"]').first().textContent()

        if (rawDescription && jobTitle && companyName) {
          console.log(`Scraped job: ${jobTitle} at ${companyName} from ${jobLink}`)

          const normalizedData = await normalizeJob(rawDescription)

          await createJob({
            company_id: null, // For now, leave null. We can match/create companies later.
            raw_description: rawDescription,
            normalized_data: normalizedData,
            embedding: null, // Will be generated by AI later
            status: 'active',
            source: 'indeed',
            source_url: jobLink,
          })
          console.log(`Stored job: ${jobTitle}`)
        } else {
          console.warn(`Could not scrape raw description, title, or company for job: ${jobLink}`)
        }
      } catch (jobError) {
        console.error(`Error scraping individual Indeed job ${jobLink}:`, jobError)
      }
    }
  } catch (error) {
    console.error(`Error scraping Indeed board ${searchUrl}:`, error)
  } finally {
    await browser.close()
    console.log('Browser closed.')
  }
}
