import { chromium } from 'playwright'
import { createJob } from '@/lib/db/jobs'
import { normalizeJob } from '@/lib/ai/normalize-job'

/**
 * Scrapes all active job postings from a given Lever job board URL.
 * @param boardUrl The URL of the Lever job board (e.g., https://jobs.lever.co/somecompany)
 */
export async function scrapeLeverBoard(boardUrl: string): Promise<void> {
  const browser = await chromium.launch({ headless: true })
  const context = await browser.newContext()
  const page = await context.newPage()

  try {
    await page.goto(boardUrl, { waitUntil: 'domcontentloaded' })
    console.log(`Navigated to Lever board: ${boardUrl}`)

    // Lever job boards often have a structure like:
    // <div class="posting">
    //   <a href="job_link">
    //     <h5 class="posting-title">Job Title</h5>
    //   </a>
    // </div>
    // Or sometimes a list of <a> tags directly.

    // Attempt to find company name - Lever boards might not always display it prominently
    // This is a best effort, might need refinement
    const companyName = await page.locator('h1.main-header-title, .main-header-title h1, .main-header-title').first().textContent().catch(() => null)
    console.log(`Detected company name: ${companyName || 'N/A'}`)

    // Find all job links. Lever typically uses 'a.posting-title' or similar within 'div.posting'
    const jobLinks = await page.$$eval('a.posting-title, .posting a[href*="jobs.lever.co/"]', (links: HTMLAnchorElement[]) =>
      links.map(link => link.href)
    )
    console.log(`Found ${jobLinks.length} job links.`)

    for (const jobLink of jobLinks) {
      try {
        await page.goto(jobLink, { waitUntil: 'domcontentloaded' })
        // Lever job description is often within a div with class 'section-wrapper' or 'description'
        const rawDescription = await page.locator('.section-wrapper.page-full-width, .description').textContent()
        const jobTitle = await page.locator('.posting-headline h2, h2.posting-title').textContent()

        if (rawDescription && jobTitle) {
          console.log(`Scraped job: ${jobTitle} from ${jobLink}`)

          const normalizedData = await normalizeJob(rawDescription)

          await createJob({
            company_id: null, // For now, leave null. We can match/create companies later.
            raw_description: rawDescription,
            normalized_data: normalizedData,
            embedding: null, // Will be generated by AI later
            status: 'active',
            source: 'lever', // Mark source as lever
            source_url: jobLink,
          })
          console.log(`Stored job: ${jobTitle}`)
        } else {
          console.warn(`Could not scrape raw description or title for job: ${jobLink}`)
        }
      } catch (jobError) {
        console.error(`Error scraping individual job ${jobLink}:`, jobError)
      }
    }
  } catch (error) {
    console.error(`Error scraping Lever board ${boardUrl}:`, error)
  } finally {
    await browser.close()
    console.log('Browser closed.')
  }
}